### ISSUE TITLE
Client can't be refilled with new DC

### ISSUE THREAD

**Issue by ipfsforcezuofu** [fidlabs/allocator-tooling#72]
The issue is described in slack https://filecoinproject.slack.com/archives/C06MTBZ44P2/p1725421991465689

My allocator account is f03019856. I successfully distributed 125t to client f3sb5dxwwoeawhj4cxdhb5ir5qadc3p7cocxw4i7gem2iuj6isvthkz6dqj2btdxxa7behz22l2ve3bd76viva. However, I’m unable to refill on https://allocator.tech/. When checking the account on https://verify.glif.io/, it indicates that the address is not a verified client. Attached is a link to issue number https://github.com/ipfsforcezuofu/ipfsforce-allocator/issues/8, along with a screenshot. Could someone please investigate this?
[Client Address Issue.pdf](https://github.com/user-attachments/files/16863072/Client.Address.Issue.pdf)

**Comment by willscott** [comment]
Hi @ipfsforcezuofu  - per
https://datacapstats.io/notaries/f03019856

you can see that the 125tb was distributed and is generally accounted for, to the f0 stable address, rather than the f3 address (which you'll see also listed on the right of the page)

You can see that the client has precisely used all 125tb of it's allocation (4000 datacap ddo claims), and so has no remaining data-cap balance. At the point that it has a 0 balance, it will be removed from the 'verified clients' list, as it has no datacap to spend currently.

This should be independent of your ability to refill / send more datacap to the client.

**Comment by kacperzuk-neti** [comment]
@ipfsforcezuofu I've pushed a fix for this, please check if you can trigger the refill on allocator.tech now.

**Comment by ipfsforcezuofu** [comment]
@kacperzuk-neti 
It can trigger the refill now. thanks.
