### ISSUE TITLE
DC assignment doubled

### ISSUE THREAD

**Issue by Filedrive-ops** [fidlabs/allocator-tooling#79]
My client [regarding Filecoin-Plus-Pathway Issue #3 ](https://github.com/filedrive-team/Filecoin-Plus-Pathway/issues/3) informed me that the 200 TiB DC assignment has been fully utilized. However, the tool still shows 200 TiB as unused. I recall confirming the proposal twice. Could this have led to a double DC assignment? Could you please investigate?
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/a293b4fc-618e-4500-a033-aafd853e54ab">

**Comment by kacperzuk-neti** [comment]
So for this client https://github.com/filedrive-team/Filecoin-Plus-Pathway/issues/3 there were indeed 2 assignments made today:
* https://filfox.info/en/message/bafy2bzaceaaes7lf2mw6wgb5qsksa5c3ldymjcrn4frtx4oq4conoguih3pmc?t=2
* https://filfox.info/en/message/bafy2bzacecezzfuim3h6xkscklvmgxpkt2jo3hn4jqvxmcadgtmxcf7xdwcea?t=2

But only the 2nd one was actually registered in allocator.tech. So indeed something went wrong here.

We'll investigate the root cause and update the state of the application to include the missing allocation.

In the meantime, do you remember any errors showing up after confirming the first proposal?

**Comment by Filedrive-ops** [comment]
@kacperzuk-neti Several minutes after executing the initial proposal, the refill status still hasn't changed to GRANTED. I just reran the process, and there were no errors throughout.

**Comment by kacperzuk-neti** [comment]
We were unable to identify the root cause, but have a plan on redesigning this flow to prevent this happening no matter what.
In the meantime, please make sure that if you confirmed an allocation on Ledger, but it didn't show up on Allocator.tech, do not retry, open an issue here for us to investigate.
I've added the lost allocation manually, so it should be reflected in allocator.tech now.

**Comment by Filedrive-ops** [comment]
@kacperzuk-neti 
Sure, , I'll reach out to technical support for any anomalies during DC allocation. Thank you for your investigation and support!
